# Hand-checked English names, keyed by the Chinese name used in OpenStreetMap.
# Intercity names follow the usual English (Wikipedia) form: "Beijing–Shanghai High-Speed Railway".

LINE_EN = {
    # ---- high-speed and intercity
    '京沪高铁': 'Beijing–Shanghai High-Speed Railway',
    '沪宁城际线': 'Shanghai–Nanjing Intercity Railway',
    '龙漳线': 'Longyan–Zhangzhou Railway',
    '杭深铁路': 'Hangzhou–Shenzhen Railway',
    '海南东环高速线': 'Hainan Eastern Ring High-Speed Railway',
    '海南西环高速线': 'Hainan Western Ring High-Speed Railway',
    '钦防铁路': 'Qinzhou–Fangchenggang Railway',
    '京哈高速线': 'Beijing–Harbin High-Speed Railway',
    '昌九城际线': 'Nanchang–Jiujiang Intercity Railway',
    '昌福线': 'Nanchang–Fuzhou Railway',
    '合福高速线': 'Hefei–Fuzhou High-Speed Railway',
    '宁杭高速线': 'Nanjing–Hangzhou High-Speed Railway',
    '成渝高速线': 'Chengdu–Chongqing Intercity Railway',
    '衡柳铁路': 'Hengyang–Liuzhou Railway',
    '衢九线': 'Quzhou–Jiujiang Railway',
    '南广铁路': 'Nanning–Guangzhou Railway',
    '青荣城际铁路': 'Qingdao–Rongcheng Intercity Railway',
    '赣瑞龙线': 'Ganzhou–Ruijin–Longyan Railway',
    '广珠城际铁路': 'Guangzhou–Zhuhai Intercity Railway',
    '江门线': 'Guangzhou–Zhuhai Intercity Railway (Jiangmen Branch)',
    '京津城际线': 'Beijing–Tianjin Intercity Railway',
    '徐兰高速线': 'Xuzhou–Lanzhou High-Speed Railway',
    '峨眉山线': 'Leshan–Emeishan Railway',
    '武咸城际铁路': 'Wuhan–Xianning Intercity Railway',
    '连镇线': 'Lianyungang–Zhenjiang High-Speed Railway',
    '合杭高速线': 'Hefei–Hangzhou High-Speed Railway',
    '大西高速线': 'Datong–Xi’an High-Speed Railway',
    '济青高速铁路': 'Jinan–Qingdao High-Speed Railway',
    '渝贵铁路': 'Chongqing–Guiyang Railway',
    '银兰高速线': 'Yinchuan–Lanzhou High-Speed Railway',
    '深湛线': 'Shenzhen–Zhanjiang Railway',
    '成灌铁路': 'Chengdu–Dujiangyan Intercity Railway',
    '离堆公园线': 'Chengdu–Dujiangyan Intercity Railway (Lidui Park Branch)',
    '怀衡线': 'Huaihua–Hengyang Railway',
    '丹大线': 'Dandong–Dalian Intercity Railway',
    '杭昌高速线杭黄段': 'Hangzhou–Huangshan High-Speed Railway',
    '杭昌高速线昌景黄段': 'Nanchang–Jingdezhen–Huangshan High-Speed Railway',
    '盘营高铁': 'Panjin–Yingkou High-Speed Railway',
    '南龙线': 'Nanping–Longyan Railway',
    '沪苏通铁路': 'Shanghai–Suzhou–Nantong Railway',
    '霸徐线': 'Bazhou–Xushui Railway',
    '武冈城际线': 'Wuhan–Huanggang Intercity Railway',
    '武孝城际铁路': 'Wuhan–Xiaogan Intercity Railway',
    '仙桃城际线': 'Wuhan–Xiantao Intercity Railway',
    '梅汕线': 'Meizhou–Shantou High-Speed Railway',
    '川南城际铁路': 'South Sichuan Intercity Railway',
    '日兰高速线': 'Rizhao–Lankao High-Speed Railway',
    '青盐线': 'Qingdao–Yancheng Railway',
    '郑阜高速铁路': 'Zhengzhou–Fuyang High-Speed Railway',
    '防东铁路': 'Fangchenggang–Dongxing Railway',
    '广深港高速线': 'Guangzhou–Shenzhen–Hong Kong Express Rail Link',
    '武西高速线': 'Wuhan–Xi’an High-Speed Railway',
    '金温线': 'Jinhua–Wenzhou Railway',
    '京雄城际线': 'Beijing–Xiong’an Intercity Railway',
    '崇礼线': 'Chongli Railway',
    '川青铁路': 'Sichuan–Qinghai Railway',
    '沪昆高速线': 'Shanghai–Kunming High-Speed Railway',
    '沪蓉线': 'Shanghai–Wuhan–Chengdu High-Speed Railway',
    '成雅线': 'Chengdu–Ya’an Railway',
    '福平线': 'Fuzhou–Pingtan Railway',
    '邕北线': 'Nanning–Beihai Railway',
    '银西高铁': 'Yinchuan–Xi’an High-Speed Railway',
    '京港高速线': 'Beijing–Hong Kong High-Speed Railway',
    '沈大高速线': 'Shenyang–Dalian High-Speed Railway',
    '徐连高速线': 'Xuzhou–Lianyungang High-Speed Railway',
    '阜黄高速线': 'Fuyang–Huanggang High-Speed Railway',
    '潍荣高速线': 'Weifang–Rongcheng High-Speed Railway',
    '盐通高速线': 'Yancheng–Nantong High-Speed Railway',
    '张吉怀高速线': 'Zhangjiajie–Jishou–Huaihua High-Speed Railway',
    '济郑高速线': 'Jinan–Zhengzhou High-Speed Railway',
    '郑渝高速线': 'Zhengzhou–Chongqing High-Speed Railway',
    '贵南高速线': 'Guiyang–Nanning High-Speed Railway',
    '长珲城际线': 'Changchun–Hunchun Intercity Railway',
    '京唐城际线': 'Beijing–Tangshan Intercity Railway',
    '京滨城际线': 'Beijing–Binhai Intercity Railway',
    '兰张高速线': 'Lanzhou–Zhangye High-Speed Railway',
    '杭台高速线': 'Hangzhou–Taizhou High-Speed Railway',
    '朝凌高速线': 'Chaoyang–Linghai High-Speed Railway',
    '弥蒙高速线': 'Mile–Mengzi High-Speed Railway',
    '津兴城际线': 'Tianjin–Daxing Airport Intercity Railway',
    '济莱高速铁路': 'Jinan–Laiwu High-Speed Railway',
    '杭温高速线': 'Hangzhou–Wenzhou High-Speed Railway',
    '京广高速线': 'Beijing–Guangzhou High-Speed Railway',
    '广汕高速铁路': 'Guangzhou–Shanwei High-Speed Railway',
    '汕汕高速铁路': 'Shanwei–Shantou High-Speed Railway',
    '南凭高速线': 'Nanning–Pingxiang High-Speed Railway',
    '巢马城际铁路': 'Chaohu–Ma’anshan Intercity Railway',
    '郫彭线': 'Pidu–Pengzhou Railway',
    '包银高铁': 'Baotou–Yinchuan High-Speed Railway',
    '楚大线': 'Chuxiong–Dali Railway',
    '广昆线': 'Guangtong–Kunming Railway',
    '津秦高速线': 'Tianjin–Qinhuangdao High-Speed Railway',
    '巴南高速线': 'Bazhong–Nanchong High-Speed Railway',
    '龙龙高速铁路': 'Longyan–Longchuan High-Speed Railway',
    '沪苏湖高速铁路': 'Shanghai–Suzhou–Huzhou High-Speed Railway',
    '渝厦高速线': 'Chongqing–Xiamen High-Speed Railway',
    '池黄高速线': 'Chizhou–Huangshan High-Speed Railway',
    '蓉昆高速铁路': 'Chengdu–Kunming High-Speed Railway',
    '渝昆高速铁路': 'Chongqing–Kunming High-Speed Railway',
    '盘兴高速铁路': 'Panzhou–Xingyi High-Speed Railway',
    '西渝高铁': 'Xi’an–Chongqing High-Speed Railway',
    '沪宁沿江高速线': 'Shanghai–Nanjing Riverside High-Speed Railway',
    '集大原高速铁路': 'Jining–Datong–Yuanping High-Speed Railway',
    '福厦高速铁路': 'Fuzhou–Xiamen High-Speed Railway',
    '宣绩高速线': 'Xuancheng–Jixi High-Speed Railway',
    '南珠高速线': 'Nanning–Zhuhai High-Speed Railway',
    '广湛高速线': 'Guangzhou–Zhanjiang High-Speed Railway',
    '襄荆高速线': 'Xiangyang–Jingmen High-Speed Railway',
    '荆荆高速线': 'Jingmen–Jingzhou High-Speed Railway',
    '沪渝蓉高速铁路': 'Shanghai–Chongqing–Chengdu High-Speed Railway',
    '淮宿蚌城际铁路': 'Huaibei–Suzhou–Bengbu Intercity Railway',
    '淮宿阜城际铁路': 'Huaibei–Suzhou–Fuyang Intercity Railway',
    '潍烟高速线': 'Weifang–Yantai High-Speed Railway',
    '沈佳高速线': 'Shenyang–Jiamusi High-Speed Railway',
    '甬广高速铁路': 'Ningbo–Guangzhou High-Speed Railway',
    '杭衢高速铁路': 'Hangzhou–Quzhou High-Speed Railway',
    '哈伊高速线': 'Harbin–Yichun High-Speed Railway',
    '合新高速线': 'Hefei–Xinyi High-Speed Railway',
    '包西高速线': 'Baotou–Xi’an High-Speed Railway',
    '金建高速线': 'Jinhua–Jiande High-Speed Railway',
    '天蒲铁路': 'Tianfu–Pujiang Railway',
    '宁淮城际铁路': 'Nanjing–Huai’an Intercity Railway',
    # ---- conventional trunk lines
    '兰新线': 'Lanzhou–Xinjiang Railway',
    '京九线': 'Beijing–Kowloon Railway',
    '京广线': 'Beijing–Guangzhou Railway',
    '沪昆线': 'Shanghai–Kunming Railway',
    '塔韩线': 'Tahe–Hanjiagou Railway',
    '青藏线': 'Qinghai–Tibet Railway',
    '陇海线': 'Longhai Railway',
    '焦柳线': 'Jiaozuo–Liuzhou Railway',
    '京沪线': 'Beijing–Shanghai Railway',
    '川藏铁路': 'Sichuan–Tibet Railway',
    '南疆线': 'Southern Xinjiang Railway',
    '临哈线': 'Linhe–Hami Railway',
    '瓦日铁路': 'Watang–Rizhao Railway',
    '京哈线': 'Beijing–Harbin Railway',
    '格库线': 'Golmud–Korla Railway',
    '成昆线': 'Chengdu–Kunming Railway',
    '湘桂线': 'Hunan–Guangxi Railway',
    '唐包线': 'Tangshan–Baotou Railway',
    '包兰线': 'Baotou–Lanzhou Railway',
    '益湛线': 'Yiyang–Zhanjiang Railway',
    '宁西线': 'Nanjing–Xi’an Railway',
    '滨洲线': 'Harbin–Manzhouli Railway',
    '集通线': 'Jining–Tongliao Railway',
    '(原)浙赣线': 'Zhejiang–Jiangxi Railway',
    '(原)湘黔线': 'Hunan–Guizhou Railway',
    '包西铁路': 'Baotou–Xi’an Railway',
    '和若线': 'Hotan–Ruoqiang Railway',
    '南昆线': 'Nanning–Kunming Railway',
    '襄渝线': 'Xiangyang–Chongqing Railway',
    '京通线': 'Beijing–Tongliao Railway',
    '兰渝线': 'Lanzhou–Chongqing Railway',
    '太中线': 'Taiyuan–Zhongwei Railway',
    '浩吉线': 'Haoji Railway',
    '鹰厦线': 'Yingtan–Xiamen Railway',
    '嫩林线': 'Nenjiang–Gulian Railway',
    '敦煌线': 'Dunhuang Railway',
    '宝成线': 'Baoji–Chengdu Railway',
    '峨广线': 'Emei–Guangtong Railway',
    '渝怀线': 'Chongqing–Huaihua Railway',
    '京包线': 'Beijing–Baotou Railway',
    '朔黄线': 'Shuozhou–Huanghua Railway',
    '中老昆万线': 'China–Laos Railway',
    '(原)贵昆线': 'Guiyang–Kunming Railway',
    '锡乌线': 'Xilinhot–Ulanqab Railway',
    '图佳线': 'Tumen–Jiamusi Railway',
    '平齐线': 'Siping–Qiqihar Railway',
    '皖赣线': 'Anhui–Jiangxi Railway',
    '长图线': 'Changchun–Tumen Railway',
    '南同蒲线': 'Southern Tongpu Railway',
    '北同蒲线': 'Northern Tongpu Railway',
    '内六线': 'Neijiang–Liupanshui Railway',
    '成渝线': 'Chengdu–Chongqing Railway',
    '滨绥线': 'Harbin–Suifenhe Railway',
    '新长线': 'Xinyi–Changxing Railway',
    '喀和线': 'Kashgar–Hotan Railway',
    '宝中铁路': 'Baoji–Zhongwei Railway',
    '奎北线': 'Kuytun–Beitun Railway',
    '兴泉线': 'Xingguo–Quanzhou Railway',
    '黔桂铁路': 'Guizhou–Guangxi Railway',
    '沈吉线': 'Shenyang–Jilin Railway',
    '沈山线': 'Shenyang–Shanhaiguan Railway',
    '牙林线': 'Yakeshi–Linhai Railway',
    '通让线': 'Tongliao–Rangzhan Railway',
    '川黔铁路': 'Sichuan–Guizhou Railway',
    '通霍线': 'Tongliao–Huolinhe Railway',
    '沈大线': 'Shenyang–Dalian Railway',
    '锦承线': 'Jinzhou–Chengde Railway',
    '京原线': 'Beijing–Yuanping Railway',
    '汉丹铁路': 'Hankou–Danjiangkou Railway',
    '峰福线': 'Hengfeng–Fuzhou Railway',
    '衢宁线': 'Quzhou–Ningde Railway',
    '太焦线': 'Taiyuan–Jiaozuo Railway',
    '绥佳线': 'Suihua–Jiamusi Railway',
    '宁启铁路': 'Nanjing–Qidong Railway',
    '漳龙线': 'Zhangping–Longyan Railway',
    '白阿铁路': 'Baicheng–Arxan Railway',
    '滨北线': 'Harbin–Bei’an Railway',
    '阳安线': 'Yangpingguan–Ankang Railway',
    '达成线': 'Dazhou–Chengdu Railway',
    '集二铁路': 'Jining–Erenhot Railway',
    '广茂线': 'Guangzhou–Maoming Railway',
    '哈佳线': 'Harbin–Jiamusi Railway',
    '长白线': 'Changchun–Baishan Railway',
    '黎湛线': 'Litang–Zhanjiang Railway',
    '新兖铁路': 'Xinxiang–Yanzhou Railway',
    '兖石线': 'Yanzhou–Shijiusuo Railway',
    '津山线': 'Tianjin–Shanhaiguan Railway',
    '胶新铁路': 'Jiaozhou–Xinyi Railway',
    '精霍线': 'Jinghe–Khorgas Railway',
    '赣龙线': 'Ganzhou–Longyan Railway',
    '锦赤线': 'Jinzhou–Chifeng Railway',
    '吉衡线': 'Ji’an–Hengyang Railway',
    '合九线': 'Hefei–Jiujiang Railway',
    '北黑线': 'Bei’an–Heihe Railway',
    '广达线': 'Guangyuan–Dazhou Railway',
    '邯济线': 'Handan–Jinan Railway',
    '石长线': 'Shimen–Changsha Railway',
    '神朔铁路': 'Shenmu–Shuozhou Railway',
    '西平铁路': 'Xi’an–Pingliang Railway',
    '沈丹线': 'Shenyang–Dandong Railway',
    '拉日线': 'Lhasa–Shigatse Railway',
    '梅集线': 'Meihekou–Ji’an Railway',
    '石太线': 'Shijiazhuang–Taiyuan Railway',
    '京承线': 'Beijing–Chengde Railway',
    '西康铁路': 'Xi’an–Ankang Railway',
    '淮南线': 'Huainan Railway',
    '邯长线': 'Handan–Changzhi Railway',
    '昆河线': 'Kunming–Hekou Railway',
    '武九线': 'Wuchang–Jiujiang Railway',
    '铜九线': 'Tongling–Jiujiang Railway',
    '大准铁路': 'Datong–Jungar Railway',
    '拉林铁路': 'Lhasa–Nyingchi Railway',
    '大临线': 'Dali–Lincang Railway',
    '渝利线': 'Chongqing–Lichuan Railway',
    '宜万线': 'Yichang–Wanzhou Railway',
    '汉宜线': 'Hankou–Yichang Railway',
    '石德铁路': 'Shijiazhuang–Dezhou Railway',
    '胶济线': 'Qingdao–Jinan Railway',
    '萧甬线': 'Xiaoshan–Ningbo Railway',
    '宣杭线': 'Xuancheng–Hangzhou Railway',
    '广深线': 'Guangzhou–Shenzhen Railway',
}

# Urban lines whose names are not "N号线": (English name, badge text or None to keep).
URBAN = {
    '北京地铁首都机场线': ('Capital Airport Express', 'CA'),
    '北京地铁大兴机场线': ('Daxing Airport Express', 'DA'),
    '北京地铁昌平线': ('Changping Line', 'CP'),
    '北京地铁房山线': ('Fangshan Line', 'FS'),
    '北京地铁燕房线': ('Yanfang Line', 'YF'),
    '北京地铁亦庄线': ('Yizhuang Line', 'YZ'),
    '北京地铁西郊线': ('Xijiao Line', 'XJ'),
    '北京地铁S1线': ('Line S1', 'S1'),
    '北京地铁4号线/大兴线': ('Line 4 / Daxing Line', '4'),
    '北京地铁八通线': ('Batong Line', 'BT'),
    '北京地铁大兴线': ('Daxing Line', 'DX'),
    '城市副中心线': ('Sub-Central Line', 'S'),
    '北京市郊铁路S2线': ('Suburban Railway S2', 'S2'),
    '北京市郊铁路怀柔－密云线': ('Huairou–Miyun Line', 'S5'),
    '北京市郊铁路通密线': ('Tongzhou–Miyun Line', 'S6'),
    '亦庄新城现代有轨电车T1线': ('Yizhuang Tram T1', 'T1'),
    '前门大街有轨电车': ('Qianmen Street Tram', 'QM'),
    '八达岭地面缆车': ('Badaling Funicular', None),
    '北京雄安R1线': ('Beijing–Xiong’an Line R1', 'R1'),
    '上海磁浮示范运营线': ('Shanghai Maglev', 'MAG'),
    '上海地铁浦江线': ('Pujiang Line', 'PJ'),
    '金山铁路': ('Jinshan Railway', 'JS'),
    '市域机场线': ('Airport Link Line', 'AL'),
    '上海浦东机场旅客捷运系统西线': ('Pudong Airport APM (West)', 'APM'),
    '上海浦东机场旅客捷运系统东线': ('Pudong Airport APM (East)', 'APM'),
    '松江有轨电车1号线': ('Songjiang Tram T1', 'T1'),
    '松江有轨电车2号线': ('Songjiang Tram T2', 'T2'),
    '地铁': ('Zhujiang New Town APM', 'APM'),
    '地铁 广佛线': ('Guangfo Line', 'GF'),
    '海珠有轨1号线': ('Haizhu Tram Line 1', 'THZ1'),
    '黄埔有轨电车1号线': ('Huangpu Tram Line 1', 'THP1'),
    '黄埔有轨电车2号线': ('Huangpu Tram Line 2', 'THP2'),
    '广清城际': ('Guangzhou–Qingyuan Intercity', 'GQ'),
    '广肇-广惠城际': ('Guangzhou–Zhaoqing / Guangzhou–Huizhou Intercity', 'GZ'),
    '广州东环-琶莲-佛莞城际': ('Guangzhou East Ring / Foshan–Dongguan Intercity', 'FG'),
    '广州东环-广佛南环城际': ('Guangzhou East Ring / Guangfo South Ring Intercity', 'GF'),
    '广深城际': ('Guangzhou–Shenzhen Intercity', 'GS'),
    '穗深城际': ('Guangzhou–Shenzhen Intercity (Airport)', 'SS'),
    '穗深城际快车': ('Guangzhou–Shenzhen Intercity Express', 'SS'),
    '琶莲-佛莞-穗深城际快车': ('Pazhou–Foshan–Dongguan–Shenzhen Express', 'PS'),
    '天府机场APM': ('Tianfu Airport APM', 'APM'),
    '成都市域铁路S3资阳线': ('Ziyang Line (S3)', 'S3'),
    '西户线': ('Xi’an–Huxian Line', 'XH'),
    '西安高新云巴线': ('Gaoxin SkyShuttle', 'YB'),
    '济南轨道交通云巴线': ('SkyShuttle Line', 'YB'),
    '济南轨道交通济阳线': ('Jiyang Line', 'JY'),
    '长沙地铁3号线南延': ('Line 3 South Extension', '3'),
    'Changsha Maglev Express': ('Changsha Maglev Express', 'MAG'),
    '大王山云巴': ('Dawangshan SkyShuttle', 'Y1'),
    '黄石现代有轨电车': ('Huangshi Tram', 'T1'),
    '氢淞号有轨电车': ('Qingsong Hydrogen Tram', 'QS'),
    '氢春号有轨电车': ('Qingchun Hydrogen Tram', 'QC'),
    '辽源氢能文旅列车1号线': ('Hydrogen Tourist Train Line 1', '1'),
    '辽源氢能文旅列车2号线': ('Hydrogen Tourist Train Line 2', '2'),
    '昆明长水国际机场捷运': ('Changshui Airport APM', 'APM'),
    '都江堰M-TR旅游客运专线': ('Dujiangyan M-TR Tourist Line', 'MTR'),
    '都江堰M-TR旅游客运专线都江堰支线': ('Dujiangyan M-TR (Dujiangyan Branch)', 'MTR'),
    '桂林云轨示范线': ('Guilin SkyRail Demonstration Line', 'Y1'),
    '清远长隆磁浮旅游专线': ('Qingyuan Chimelong Maglev', 'QY'),
    '天水有轨电车1号线': ('Tram Line 1', 'T1'),
    '天水有轨电车2号线': ('Tram Line 2', 'T2'),
    '华为松山湖有轨电车3号线': ('Huawei Songshan Lake Tram', 'T3'),
    '高新有轨电车1号线': ('New District Tram Line 1', 'T1'),
    '高新有轨电车2号线': ('New District Tram Line 2', 'T2'),
    '淮安有轨电车1号线': ('Tram Line 1', 'T1'),
    '长寿缆车': ('Changshou Funicular', None),
    '港鐵迪士尼綫': ('Disneyland Resort Line', 'DRL'),
    'APM T1': ('Airport APM', 'APM'),
    '澳門輕軌石排灣線': ('Seac Pai Van Line', 'SPV'),
    '橫琴線': ('Hengqin Line', 'HQ'),
    '杭海城际铁路': ('Hangzhou–Haining Intercity', 'HH'),
    '重庆轨道交通环线': ('Loop Line', '环'),
    '重庆轨道交通4–环–5直通快速': ('Line 4–Loop–5 Express', 'EX'),
    '璧山云巴1号线': ('Bishan SkyShuttle', 'Y1'),
    '坪山云巴 1号线': ('Pingshan SkyShuttle', 'Y1'),
    '比亚迪云轨': ('BYD SkyRail', 'YG'),
    '天津地铁津静线': ('Jinjing Line', 'JJ'),
    '郑许线': ('Zhengzhou–Xuchang Line', 'ZX'),
    '南京地铁S1-S7贯通特快': ('Line S1–S7 Express', 'S1'),
    '南京地铁S2号线/宁马线': ('Line S2 (Nanjing–Ma’anshan)', 'S2'),
    '南京河西有轨电车': ('Hexi Tram', 'HX'),
    '南京麒麟有轨电车': ('Qilin Tram', 'QL'),
    '有轨 高明区现代有轨电车示范线': ('Gaoming Tram', 'GM'),
    '宁滁线': ('Nanjing–Chuzhou Line', 'S4'),
    '眉山城际线': ('Meishan Intercity Line', 'S5'),
    '香港電車': ('Hong Kong Tramways', 'TRAM'),
    '港鐵荃灣綫': ('Tsuen Wan Line', 'TWL'),
    '光谷有轨电车L1线': ('Optics Valley Tram L1', 'L1'),
    '光谷有轨电车L2线': ('Optics Valley Tram L2', 'L2'),
    '长沙磁浮快线': ('Changsha Maglev Express', 'MAG'),
    '连云港市郊铁路': ('Lianyungang Suburban Railway', 'S'),
    '青平快线': ('Qingdao–Pingdu Express', 'QP'),
    '深圳市 轻轨': ('Light Rail', None),
    '金华轨道交通金义东线 义东段': ('Jinhua–Yiwu–Dongyang Line (Yiwu–Dongyang)', '义东'),
    '金华轨道交通金义东线 金义段': ('Jinhua–Yiwu–Dongyang Line (Jinhua–Yiwu)', '金义'),
}

STATION_EN = {
    '金融岛北': 'Jinrongdao North',
    '乔庄东': 'Qiaozhuang East',
    '珠海机场': 'Zhuhai Airport',
}

# Native names for lines mapped only as a route description.
LINE_ZH = {
    '磁浮机场站→磁浮高铁站': '长沙磁浮快线',
}

# Urban lines that are not public transport, by native name (or English name when there is none).
NOT_PUBLIC = {
    '桂林云轨示范线': 'demonstration line without public service',
    '海洋列車': 'theme-park funicular (Ocean Park)',
    '上海浦东机场旅客捷运系统西线': 'airside people mover',
    '上海浦东机场旅客捷运系统东线': 'airside people mover',
    'APM T1': 'airside people mover',
    'Hong Kong International Airport Automated People Mover': 'airside people mover',
}

# Freight-only railways (no scheduled passenger trains, 2025–26). Matched on the name
# with 线/铁路 variants. Researched from news and Wikipedia snippets; the low-confidence
# ones (大准, 锡乌, 神朔, 邯黄, 黄万, 将淖, 三新, 大莱龙) should be checked against 12306.
# freight, hub-ring, port and coal lines found by the world audit (2026-09)
FREIGHT_AUDIT = ["一零一", "上兰村", "上宁", "东海岛", "东铜", "于虎", "云岗", "井西", "何杨", "六盘水南环", "兴珞", "准神", "北杨", "南何", "南堡", "南昌枢纽西环", "叉石支", "吴泾", "吴高", "周支", "天津大北环", "夹北", "宁波北环", "宝东", "小西", "徐圩支", "成都北环", "成都西环", "斗尾", "林浦", "柴木", "武昌南环", "沈于", "沈山北道", "沪春", "海沧支", "淖毛湖", "滨江", "田东", "白石湖支", "石家庄西环", "西固城", "西张", "边海", "金窑", "钦州港东", "防城港企沙支", "鸳梅"]
FREIGHT = ['大秦', '朔黄', '神黄', '准池', '准朔', '大准', '黄大', '唐包', '唐呼', '张唐', '蒙冀', '迁曹', '唐港',
           '神朔', '包神', '甘泉', '巴准', '塔韩', '新准', '三新', '准兴', '巴新', '锡乌', '侯月', '邯黄', '黄万',
           '嘉策', '额哈', '红淖', '将淖', '哈罗', '李港', '北仑', '浦东', '平南', '平盐', '益羊', '大莱龙', '瓦日']
